package polytech.cloud.groupa.model;

import javax.persistence.*;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Objects;

/**
 * This class represents a Position object with latitude, longitude and a unique id
 *
 * @author Ewald Janin, Felix Martelin
 */
@Entity
@Table(name = "Position")
public class Position implements Serializable {

    /**
     * Autogenerated unique identifier
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "positionId", nullable = false, insertable = false, updatable = false)
    private long positionId;

    /**
     * latitude, using BigDecimal to avoid precision loss
     *
     * @see BigDecimal
     */
    @Basic
    @Column(name = "lat", nullable = false, precision = 8, scale = 12)
    private BigDecimal lat;

    /**
     * longitude, using BigDecimal to avoid precision loss
     *
     * @see BigDecimal
     */
    @Basic
    @Column(name = "lon", nullable = false, precision = 8, scale = 12)
    private BigDecimal lon;


    public long getPositionId(){
        return this.positionId;
    }

    public void setPositionId(long positionId) {
        this.positionId = positionId;
    }

    public BigDecimal getLat() {
        return lat;
    }

    public void setLat(BigDecimal lat) {
        this.lat = lat;
    }

    public BigDecimal getLon() {
        return lon;
    }

    public void setLon(BigDecimal lon) {
        this.lon = lon;
    }

    @Override
    public String toString() {
        return String.format("Position [positionId: %d, lat: %s, lon: %s]", positionId, lat, lon);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Position position = (Position) o;
        return positionId == position.positionId &&
                Objects.equals(lat, position.lat) &&
                Objects.equals(lon, position.lon);
    }

    @Override
    public int hashCode() {
        return Objects.hash(positionId, lat, lon);
    }
}
