version: 2.1
orbs:
  maven: circleci/maven@1.0.0
  node: circleci/node@4.1.0

jobs:
  install_node_test_project:
    executor: node/default
    steps:
      - run: git clone https://github.com/Slashgear/cloud-client-eval.git
     # - run: cd ./cloud-client-eval &&
      - run: cd ./cloud-client-eval && npm install

      - run: cd ./cloud-client-eval && npm run step:1

      - run: cd ./cloud-client-eval && npm run step:2

      - run: cd ./cloud-client-eval && npm run step:3

      - run:cd ./cloud-client-eval &&  npm run step:3bis

      
workflows:
  version: 2
  tests:
    jobs:
      #- maven/test
      - install_node_test_project