version: 2
orbs:
  maven: circleci/maven@1.0.0
  node: circleci/node@4.1.0

jobs:
  install_node_test_project:
    executor: node/default
    steps:
      - run:
        command: |
          git clone https://github.com/Slashgear/cloud-client-eval.git
          cd ./cloud-client-eval 
          npm install
          npm run step:1
          npm run step:2
          npm run step:3
          npm run step:3bis
      
workflows:
  version: 2
  tests:
    jobs:
      #- maven/test
      - install_node_test_project