version: 2.1
orbs:
  maven: circleci/maven@1.0.0
  java: ci-poc/java@0.0.22
  node: circleci/node@4.1.0

jobs:
  install_node_test_project:
    executor: node/default
    steps:
      - run: git clone https://github.com/Slashgear/cloud-client-eval.git
      - run: cd ./cloud-client-eval && npm install

      - run: cd ./cloud-client-eval && npm run step:1

      - run: cd ./cloud-client-eval && npm run step:2

      - run: cd ./cloud-client-eval && npm run step:3

      - run: cd ./cloud-client-eval &&  npm run step:3bis

  clean_install:
    executor: maven/default
    steps:
      - checkout
      - run: mvn clean install -Ptest
      - run: mvn verify 
      - run: java -jar 0.0.1-SNAPSHOT.jar&

  test:
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout
      - run: mvn clean install -Powasp-dependency-check



      
workflows:
  version: 2
  tests:
    jobs:
      - test
      - clean_install
      - install_node_test_project:
          requires:
            - clean_install
      - maven/test