version: 2.1
orbs:
  maven: circleci/maven@1.0.0
  java: ci-poc/java@0.0.22
  node: circleci/node@4.1.0

jobs:

  clean_install_and_tests:
    machine: # executor type
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: sudo apt-get update -y
      - run: sudo apt-get install net-tools -y
      - run: sudo apt-get install ufw -y
      - run: sudo ufw allow 80
      - run: sudo ufw allow http
      - run: sudo ufw allow enable
      - run: sudo ufw status verbose
      - run: sudo apt-get install nodejs npm -y
      - run: git clone https://github.com/marsuraa/cloud-client-eval.git
      - run: cd ./cloud-client-eval && npm install
      - run: sudo apt-get install maven -y
      - run: mvn clean verify
      - run: java -jar target/groupa-0.0.1-SNAPSHOT.jar&
      - run: sleep 30
      - run: netstat -paunt
      - run: wget -p http://localhost:8080/user
      - run: cd ./cloud-client-eval && npm test

  dependency_check:
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout
      - run: mvn clean install -Powasp-dependency-check



      
workflows:
  version: 2

  build-then-test:
    jobs:
      - dependency_check

  tests:
    jobs:
      - clean_install_and_tests
      - maven/test