version: 2
orbs:
  maven: circleci/maven@1.0.0
  node: circleci/node@4.1.0

jobs:
  install_node_test_project:
    executor: node/default
    steps:
      - run: git clone https://github.com/Slashgear/cloud-client-eval.git
     # - run:  cd ./cloud-client-eval 
      - run: npm install
        working_directory: ./cloud-client-eval 
      - run: npm run step:1
        working_directory: ./cloud-client-eval 
      - run: npm run step:2
        working_directory: ./cloud-client-eval 
      - run: npm run step:3
        working_directory: ./cloud-client-eval 
      - run: npm run step:3bis
        working_directory: ./cloud-client-eval 
      
workflows:
  version: 2
  tests:
    jobs:
      #- maven/test
      - install_node_test_project