orbs:
  maven: circleci/maven@1.0.0
  node: circleci/node@4.1.0

jobs:
  install_node_test_project:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: git clone https://github.com/Slashgear/cloud-client-eval.git
      - run: npm install

  node_tests:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm run step:1
      - run: npm run step:2
      - run: npm run step:3
      - run: npm run step:3bis

    parallelism: 4


workflows:
  version: 2
  tests:
    jobs:
      
      - install_node_test_project
      - node_tests:
          requires:
            - install_node_test_project