version: 2.1
orbs:
  maven: circleci/maven@1.0.0
  java: ci-poc/java@0.0.22
  node: circleci/node@4.1.0

jobs:

  clean_install_and_tests:
    machine: # executor type
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: mvn clean verify
      - run: java -jar 0.0.1-SNAPSHOT.jar&
      - run: apt-get update
      - run: apt-get install nodejs npm
      - run: git clone https://github.com/Slashgear/cloud-client-eval.git
      - run: cd ./cloud-client-eval && npm install
      - run: cd ./cloud-client-eval && npm run step:1
      - run: cd ./cloud-client-eval && npm run step:2
      - run: cd ./cloud-client-eval && npm run step:3
      - run: cd ./cloud-client-eval &&  npm run step:3bis

  dependency_check:
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout
      - run: mvn clean install -Powasp-dependency-check



      
workflows:
  version: 2

  build-then-test:
    jobs:
      - dependency_check

  tests:
    jobs:
      - clean_install_and_tests
      - maven/test