version: 2.1

jobs:
  owasp:
    docker:
      - image: circleci/openjdk:11.0.9
    steps:
      - checkout
      - run : maven clean install -Powasp-dependency-check
workflows:
  owasp-test:
    jobs:
      -owasp