version: 2.1
orbs:
  maven: circleci/maven@1.0.0
  java: ci-poc/java@0.0.22
  node: circleci/node@4.1.0

jobs:

  clean_install_and_tests:
    machine: # executor type
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install ufw
      - run: iptables -I INPUT 1 -i eth0 -p tcp --dport 8080 -j ACCEPT
      - run: service iptables save
      - run: service iptables restart
      - run: iptables -L
      - run: sudo apt-get install nodejs npm
      - run: git clone https://github.com/marsuraa/cloud-client-eval.git
      - run: cd ./cloud-client-eval && npm install
      - run: mvn clean verify
      - run: java -jar 0.0.1-SNAPSHOT.jar &
      - run: sleep 30
      - run: wget -p http://localhost:8080/user
      #- run: cd ./cloud-client-eval && npm test

  dependency_check:
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout
      - run: mvn clean install -Powasp-dependency-check



      
workflows:
  version: 2

  build-then-test:
    jobs:
      - dependency_check

  tests:
    jobs:
      - clean_install_and_tests
      - maven/test