version: 2.1
orbs:
  maven: circleci/maven@1.0.0
  node: circleci/node@4.1.0

jobs:
  install_node_test_project:
    executor: node/default
    steps:
      - run:
        command: git clone https://github.com/Slashgear/cloud-client-eval.git
      - run: npm install

  node_test_1:
    steps:
      - run: npm run step:1
workflows:
  node_test:
      - install_node_test_project