orbs:
  maven: circleci/maven@1.0.0
  node: circleci/node@4.1.0

jobs:
  install_node_test_project:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: git clone https://github.com/Slashgear/cloud-client-eval.git
      - run: npm install
      - run: npm test

  node_test_1:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm run step:1

  node_test_2:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm run step:1=2

  node_test_3:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm run step:3
workflows:
  version: 2
  tests:
    jobs:
      
      - install_node_test_project
      - node_test_1:
          requires:
            - install_node_test_project

      - node_test_2:
          requires:
            - install_node_test_project

      - node_test_3:
          requires:
            - install_node_test_project

      - maven/test