version: 2.1
orbs:
  maven: circleci/maven@1.0.0
jobs:
  install_node_test_project:
    docker: 
      - image: circleci/node:latest

      #- image: circleci/mysql:latest
        environment:
          MYSQL_DATABASE: bltnqtwwulzbsp3yfedg
          MYSQL_USER: urxmgpnqgbgcomuu
          MYSQL_PASSWORD: Kj8TztcuYLjMjIbECceL
    steps:
      - run: git clone https://github.com/Slashgear/cloud-client-eval.git

      
workflows:
  version: 2
  tests:
    jobs:
      #- maven/test
      - maven/build
      - install_node_test_project:
          requires:
            - maven/build